load_path: "./experiments/my_experiment/ha/model"
dataset_path: "masakhane/masakhanews"

training_parameters:
  model_type: "deberta"
  task: "classification"
  max_length: 512
  num_train_epochs: 10
  batch_size: 32
  lr: 1e-3
  padding_strategy: "max_length"

export: false
push_to_hub: false