# load_path: "WikiQuality/raw_wiki"

pre_filter:
  script_regex: true
  lang_id: false
  char_cutoff: 100

partition:
  method: "balanced_chars"
  metric: ["length", "unique_trigrams"]
  join_method: "intersection"

split:
  test_size: 0.1
  seed: 42
  shuffle: true

export: false
push_to_hub: false