#load_path: "./experiments/test/ha/model"

tokenizer_config:
  model:
    type: "bpe"
  vocab_size: "auto"
  use_sp_backend: true
  sp_kwargs:
    byte_fallback: false

merge_with: "meta-llama/Llama-2-7b-hf"

export: true
push_to_hub: true