load_path: "your-load-path"

pre_filter:
  script_regex: true
  apply_c4_filter: true

deduplicate:
  exact_match: true
  min_hash: true
  jaccard_threshold: 0.85
  n_shingles: 3
  tokenizer: "your-tokenizer"

threshold:
  thresholds: # Using gopher thresholds here
    length_words: 5
    doc_mean_word_length: 3
    frac_lines_end_ellipsis: 0.3
    frac_symbol_to_words: 0.1
    frac_no_script_words: 0.8

partition:
  metrics:
    - "length_words"
    - "doc_mean_word_length"
    - "frac_lines_end_ellipsis"
    - "frac_symbol_to_words"
    - "frac_no_script_words"
  split_method: "balanced_chars"
  quality: false

export: true
push_to_hub: true