load_path: "WikiQuality/pre_filtered"

partition:
  method: "elbow"
  metrics: "length"
  join_method: "scores"
  quality: true

split:
  test_size: 0.1
  seed: 42
  shuffle: true

export: true
push_to_hub: true