load_path: "./experiments/my_experiment/ha/model"
dataset_path: "masakhane/masakhapos" # train_path, validation_path, test_path
columns: false # text column, label column
# train_path, # valid_path, # test_path
training_parameters:
  model_type: "deberta"
  task: "pos"
  max_length: 512
  num_train_epochs: 30
  batch_size: 32
  lr: 5e-05 # do not change this for sentiment analysis
  padding_strategy: "max_length"

export: false
push_to_hub: false
checkpoint: true
