load_path: "./config/model/tiny_deberta/config.json"

training_parameters:
  model_type: "deberta"
  task: "mlm"
  max_length: 512
  mask_prob: 0.4
  num_train_epochs: 1
  batch_size: 8
  lr: 1e-03 #DO NOT CHANGE THIS
  num_eval_steps: 500

test_path: "WikiQuality/raw_wiki"
export: true
push_to_hub: false
checkpoint: false