load_path: "./config/model/tinystories/config.json"

training_parameters:
  model_type: "gpt_neo"
  task: "clm"
  max_length: 128
  num_train_epochs: 5
  batch_size: 128
  lr: 1e-02 #DO NOT CHANGE THIS
#  num_eval_steps: None
  padding_strategy: "longest"
  grad_accumulation_steps: 1
  mixed_precision: "bf16"

test_path: "WikiQuality/raw_wiki"
export: false
push_to_hub: false
checkpoint: false