slurm_partition: gpu_v100
slurm_time: "00:20:00"
slurm_additional_parameters: 
  clusters: genius
  account: lp_lagom
  nodes: 1
  cpus_per_gpu: 4
  gpus_per_node: 1
  mail_type: "BEGIN,END,FAIL"
  mail_user: 
