slurm_partition: gpu_h100
slurm_time: "18:00:00"
slurm_additional_parameters: 
  clusters: wice
  account: lp_lagom
  nodes: 1
  cpus_per_gpu: 16
  gpus_per_node: 1
  mail_type: "BEGIN,END,FAIL"
  mail_user: 
